### ISSUE TITLE
issue running mongo-subs package on Node 0.10

### ISSUE THREAD

**Issue by micabe** [safetrax/mongo-subs#10]
I have got this error:
util.js:556
  ctor.prototype = Object.create(superCtor.prototype, {
                          ^
TypeError: Object prototype may only be an Object or null
    at Function.create (native)
    at Object.exports.inherits (util.js:556:27)
    at Object.<anonymous> (/var/lib/openshift/574a2f9a2d5271dc460001b0/app-root/runtime/repo/node_modules/mongo-subs/lib/src/mongosubs.js:63:6)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/lib/openshift/574a2f9a2d5271dc460001b0/app-root/runtime/repo/node_modules/mongo-subs/lib/src/publisher.js:19:22)

Can you do sthg about it ?

Thanks,
Mickael

**Comment by micabe** [comment]
its probably due to conflicting global variable in your package..
cf: http://stackoverflow.com/questions/30426420/node-js-object-prototype-may-only-be-an-object-or-null-with-redis

**Comment by VigneshPeriasami** [comment]
Haven't checked this library below node v4, Let me check if it can be back ported. 
Thanks for the stack trace.

**Comment by VigneshPeriasami** [comment]
@micabe I have released a patch fix please upgrade to `v0.0.12`.

**Comment by micabe** [comment]
Thanks @vignesh-iopex for having fixed it so quickly!

**Comment by micabe** [comment]
Hello @vignesh-iopex,
I have another request not related to the feed..
Do you know a cheap hosting plan to deploy a node.js, mongodb with oplog enabled and with wesocket support webapp ?

Thank you, Mickael

**Comment by VigneshPeriasami** [comment]
@micabe I recently bought some from Google, not sure if there are other best options.

Ping me on `Twitter: @vikki_logs`
